### PR TITLE
Please someone review this change.

### PR DESCRIPTION
**Pull request by adrianlfns**
When I'm uploading a sample QRDA Cat1 file see a sample (https://raw.githubusercontent.com/adrianlfns/SAMPLE_QRDA/master/Test.xml), the import fails.

The proposed change is the only thing that fixes this issue for me...

I'm not sure if is correct.

### CODE REVIEW

**Comment by petercyli** [comment]
Can you describe how you are uploading the CAT1 file?  Is it just a single .xml file vs. a zipped file?

**Comment by adrianlfns** [comment]
Hello, I'm uploading a single .xml using a PopHeatlh API function. 

See the https://github.com/OSEHRA/popHealth/blob/master/app/controllers/api/reports_controller.rb

see line 352,  api :GET, "/reports/cat1/:id/:measure_ids"

To give you more Ideas. The error happens when the node  <sdtc:inFulfillmentOf1 typeCode="FLFS">
is present inside the node that represents Communication: From provider to provider.

thank you

**Comment by adrianlfns** [comment]
Any update on this??

**Comment by osehr-agent** [comment]
I’m waiting for one of the developer to verify.  He has been very busy lately.

 

I hope to get an response quickly from him to merge the code.

 

Apologize for the delay.

**Pull request merged**
